### ISSUE TITLE
Missing xgutils website

### ISSUE THREAD

**Issue by Mu-Yanchen** [QhelDIV/kitti360_renderer#1]
Thanks for your work!
Sorry to bother you, the xgutils address in the repository is no longer valid, may I ask where can I get the latest version？

**Comment by QhelDIV** [comment]
Sorry for the inconvenience. I have updated the repo with an archived version (48f32ce) of the xgutils. Please have a check.

**Comment by Mu-Yanchen** [comment]
Thank you for your quick response and updated the repo! I will close this issue, Thanks again for your work!
