### ISSUE TITLE
Question about the camera position

### ISSUE THREAD

**Issue by Mu-Yanchen** [QhelDIV/kitti360_renderer#2]
Hello! sorry for interrupting you.
This is probably a beginner's question, I want to know why in the README.md,  the code sample 40 camera positions but with just 1 pics. How can I get the others 39 camera positions gt pics?
**camera_coords**: (Nx40x3) camera coordinates. For each camera position (which is regarded as a individual scene), we generate 40 sampled camera positions.

**Comment by sherwinbahmani** [comment]
Hi,

The model is trained with GAN loss so there is no grountruth matching in the training anyway. So the other cameras are mainly sampled to make the camera distribution more diverse for training. Sampling many random views is important in 3D GAN training. If you don‘t need this, you can also just try to use the gt pose.

**Comment by Mu-Yanchen** [comment]
Thank you for your prompt response!
